CREATE TABLE IF NOT EXISTS payments (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT NOT NULL,
  username VARCHAR(255) NOT NULL,
  status VARCHAR(100) NOT NULL,
  processed_at TIMESTAMP NOT NULL
);
