apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-server-config
  labels:
    app: discovery-server
data:
  SPRING_PROFILES_ACTIVE: kubernetes
  SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
