apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-config
  labels:
    app: config-server
data:
  SPRING_PROFILES_ACTIVE: kubernetes
  SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
