apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: payment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9004
          envFrom:
            - configMapRef:
                name: payment-service-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9004
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9004
            initialDelaySeconds: 40
            periodSeconds: 20
