apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9005
          envFrom:
            - configMapRef:
                name: notification-service-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9005
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9005
            initialDelaySeconds: 40
            periodSeconds: 20
