apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  labels:
    app: api-gateway
data:
  SPRING_PROFILES_ACTIVE: kubernetes
  SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
